version: "2"
services:
  postgres:
    image: postgres
  redis:
    image: redis:3.0.7 # because of bug in qless
  api:
    build: .
    ports:
      - "8080"
    links:
      - postgres
      - redis
    logging:
      driver: "json-file"
    environment:
      NPROC: 2
      COSY_MODE: development
      COSY_BRANCH: ${COSY_BRANCH}
      REDIS_PORT: "tcp://redis:6379"
      POSTGRES_PORT: "tcp://postgres:5432"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_DATABASE: postgres
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_ID: ${AUTH0_ID}
      AUTH0_SECRET: ${AUTH0_SECRET}
      AUTH0_TOKEN: ${AUTH0_TOKEN}
      DOCKER_USER: ${DOCKER_USER}
      DOCKER_SECRET: ${DOCKER_SECRET}
